# Generated by Django 4.2.1 on 2023-05-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_rentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.customer')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.movies')),
            ],
            options={
                'unique_together': {('email_id', 'title')},
            },
        ),
    ]
