# Generated by Django 4.2.1 on 2023-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rentals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
