# Generated by Django 4.2.1 on 2023-05-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movies_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
